gettingstarted/urls.py
from django.urls import path, include
from django.contrib import admin
admin.autodiscover()
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeDoneView, PasswordChangeView
from hello.views import *
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('security/', open_site),
    path('folder/', folder, name='folder'),
    path('', folder),
    path('profiles/', Profiles, name='profiles'), 
    path('add/account', AccCreateView.as_view(), name='createacc'),
    path('add/profile', ProfCreateView.as_view(), name = 'createprof'),
    path('delete/<int:pk>/', ProfDeleteView.as_view(), name='delprof'),
    path('afterdeleting/<str:ps>/<str:login>/', afterdeleting),
    path('account/<str:pse>/', accounts, name='account'),
    path('update/<int:pk>', AccEditView.as_view(), name='edit'),
    path('new/<int:pk>', ProfDetailView.as_view()),
    path('detail/<int:pk>', AccDetailView.as_view()),
    path('accupdate/<int:pk>', AccUpdateView.as_view()),
    path('editpassword/<int:pk>/', SecEditView.as_view()),
    path('admin/', admin.site.urls),
    path('bot/start/', StartBotView.as_view()),
    path('editprofile/<int:pk>', ProfEditView.as_view(), name='editprofile'),
    path('sendmessage/<str:ps>/<str:issent>', Sendmessage, name='sendmessage'),
    path('allaccounts/', allaccounts, name='allaccount'),
    path('accounts/login/', LoginView.as_view()),
    path('changepassword/', PasswordChangeView.as_view(template_name = 'registration/change_password.html'), name='editpassword'),
    path('changepassword/done/', PasswordChangeDoneView.as_view(template_name = 'bot/newpassword.html'), name='password_change_done'),
    path('deleteacc/<int:pk>/', AccDeleteView.as_view(), name='deleteacc'),
    path('profilessortby/<str:ps>/<str:by>/', SortProfiles, name='sortprof'),
    path('allaccountssort/<str:ps>/<str:status>/<str:year>/<str:month>/', sortallaccounts, name='sortacc'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('sortfolder/<str:ps>/', sortfolder, name='sortfolder'),
    path('addadmin/', addadmin, name='addadmin'),
    path('files/<str:y>/<str:m>/<str:d>/<str:f>/', sendfile),
    path('admins/', admins, name = 'admins'),
    path('deladmin/<int:pk>', deladmin, name='deladmin'),
    path('files/<str:f>', senddocument),
    path("robots.txt", robots_txt),
    path('1459466926:AAFc46DpUlV1d7NiMxLhtY4abHhaGpQsu5I', bot_webhook, name='bot'),
    path('updatehbd/<int:pk>/', HappybirthdayEditView.as_view(), name='updatehbd'),

    path('calendar/', calendar, name='calendar'),
    path('files/contract/<str:ps>/', Contract, name='contract'),
    path('uploadcontract/<int:pk>/', ContractEditView.as_view(), name='edit_contract'),
    path('files/contract/main/<str:file>/', get_contract_main),


    
    path('content/<str:ps>', content, name='content'),
    
    path('add/audio/<str:artist>', audio_create, name='create_audio'),
    path('add/video/<str:artist>', video_create, name='create_video'),
    
    path('audio_detail/<int:pk>', AudioDetailView.as_view()),
    path('video_detail/<int:pk>', VideoDetailView.as_view()),
    
    path('delete_audio/<int:pk>', delete_audio, name='delaudio'),
    path('delete_video/<int:pk>', delete_video, name='delvideo'),

    path('update_audio/<int:pk>', AuidoEditView.as_view(), name='edit_audio'),
    path('update_video/<int:pk>', VideoEditView.as_view(), name='edit_video'),
    
    path('add_app_file/<str:artist>', generation_file, name='add_app_file'),
    path('app_list/<str:artist>', app_list, name='app_list'),
    path('open_app_file/<str:app>', open_app, name='open_app'),
]   

hello/models.py
from django.db import models

class Account(models.Model):
    pseudonym = models.CharField(null=True, max_length=40, verbose_name="Псевдоним")
    
    month = models.ForeignKey('month', null=True, on_delete=models.PROTECT, verbose_name="Месяц")
    year=models.IntegerField(null=True, verbose_name="Год")
    status = models.ForeignKey('Status', null = True, on_delete=models.PROTECT, verbose_name="Статус", blank=True)
    day_payment = models.CharField(verbose_name="Дата оплата", blank=True, null=True, max_length=30)
    document = models.FileField(upload_to='%Y/%m/%d/', null=True, blank=True)
    summa = models.CharField(max_length=20, null=True, blank=True, verbose_name="")
    published = models.DateTimeField(db_index = True, null=True, auto_now_add=True, blank=True)
    card_number = models.CharField(max_length=50, null=True, verbose_name="", blank=True)
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарии')

    notification = models.CharField(max_length=20, verbose_name='Уведомления', blank=True)
class Status(models.Model):
    s = models.CharField(max_length=20, db_index=True, null=True)
    def __str__(self):
        return self.s

class Profile(models.Model):
    published = models.CharField(max_length=50, null=True, verbose_name='Дата заключение договора')
    login = models.CharField(null=True, max_length=50, verbose_name="Логин")
    parol = models.CharField(null=True, max_length=50, verbose_name="Парол")
    pseudonym = models.CharField(null=True, max_length=50, verbose_name="Псевдоним")
    number = models.CharField(max_length=20, blank=True, verbose_name="")
    code = models.CharField(max_length=17, blank=True, verbose_name="", null=True)
    name = models.CharField(max_length=50, blank=True, verbose_name="ФИО")
    prefix = models.CharField(max_length=20, null=True, verbose_name='ID партнера')
    type_payment = models.CharField(max_length=50, null=True, verbose_name='Способ оплаты', blank=True)
    valute_card = models.CharField(max_length=10, null=True, verbose_name='Валюта карты', blank=True)
    card_number = models.CharField(max_length=30, null=True, verbose_name='', blank=True)
    date_card = models.CharField(max_length=20, null=True, blank=True, verbose_name='Срок карты')
    owner_card = models.CharField(null=True, max_length=100, verbose_name='Владелец карты', blank=True)

    date_birthday = models.CharField(max_length=30, null=True, blank=True, verbose_name='Дата рождения')
    number_passport = models.CharField(max_length=20, null=True, blank=True, verbose_name='Серия и номер паспорта')
    date_passport = models.CharField(max_length=30, null=True, blank=True, verbose_name='Дата выдачи паспорта')
    who_gave = models.CharField(max_length=100, null=True, blank=True, verbose_name='Кем выдан')
    place_registration = models.CharField(max_length=100, null=True, blank=True, verbose_name='Место регистрации')
    email = models.CharField(max_length=100, null=True, blank=True, verbose_name='E-mail')
    bank = models.CharField(max_length=100, null=True, blank=True, verbose_name='Банк')
    reward = models.CharField(max_length=200, blank=True, null=True, verbose_name='Вознаграждение')
    passport_main_st = models.FileField(verbose_name='Паспорт главная ст.', blank=True)
    passport_st_registration = models.FileField(verbose_name='Паспорт ст. регистрации', blank=True)
    signed_contract = models.FileField(verbose_name='Подписанный договор', blank=True)
    inn = models.CharField(verbose_name="ИНН", blank=True, null=True, max_length=200)

    tg_phone_number = models.CharField(null=True, max_length=40, blank=True)

    comment = models.TextField(blank=True, null=True, verbose_name='Комментарии')
class month(models.Model):
    month = models.CharField(max_length=20, null=True)
    def __str__(self):
        return self.month
        
class card(models.Model):
    pseudonym = models.CharField(max_length=50, null=True)
    card_number = models.CharField(max_length=50, null=True)
    type_payment = models.CharField(max_length=50, null=True, blank=True)
    valute_card = models.CharField(max_length=10, null=True, blank=True)
    card_number = models.CharField(max_length=30, null=True, blank=True)
    owner_card = models.CharField(null=True, max_length=100, blank=True)

class subscribersbot(models.Model):
    user_id = models.IntegerField(null=True)
    login = models.CharField(null=True, max_length=100)
    parol = models.CharField(null=True, max_length=100, blank=True)
    
class typing(models.Model):
    user_id = models.IntegerField(null=True)
    login = models.BooleanField(primary_key=False, blank=True)
    parol = models.BooleanField(primary_key=False, blank=True)
class changing(models.Model):
    user_id = models.IntegerField(null=True)
    login = models.BooleanField(primary_key=False, blank=True)
    parol = models.BooleanField(primary_key=False, blank=True)
class storage(models.Model):
    user_id = models.IntegerField(null=True)
    year = models.IntegerField(null=True, blank=True)

class security(models.Model):
    parol = models.CharField(null=True, max_length=100)



class stories(models.Model):   #all stories otchets and profiles, for table
    published = models.DateTimeField(db_index = True, null=True, auto_now_add=True)
    admin = models.CharField(max_length=100, null=True)
    obj = models.CharField(max_length=20, null=True)
    text = models.TextField(null=True)
    obj_id = models.IntegerField(null=True, blank=True)


class acc_pre_value(models.Model):
    pseudonym = models.CharField(null=True, max_length=40, verbose_name="Псевдоним")
    
    month = models.CharField(null=True, max_length=100)
    year=models.IntegerField(null=True, verbose_name="Год")
    status = models.CharField(null=True, max_length=100)
    day_payment = models.CharField(verbose_name="Дата оплата", null=True, max_length=40)
    document = models.FileField(upload_to='%Y/%m/%d/', null=True)
    summa = models.CharField(max_length=20, null=True)
    card_number = models.CharField(max_length=50, null=True)
    comment = models.TextField(blank=True, null=True, verbose_name='Комментарии')

    notification = models.CharField(max_length=20, verbose_name='Уведомления', null=True)
class prof_pre_value(models.Model):
    published = models.CharField(max_length=50, null=True, verbose_name='Дата заключение договора')
    login = models.CharField(null=True, max_length=50, verbose_name="Логин")
    parol = models.CharField(null=True, max_length=50, verbose_name="Парол")
    pseudonym = models.CharField(null=True, max_length=50, verbose_name="Псевдоним")
    number = models.CharField(blank=True, verbose_name="", null=True, max_length=100)
    code = models.CharField(max_length=5, blank=True, verbose_name="t", null=True)
    name = models.CharField(max_length=50, blank=True, verbose_name="name")
    prefix = models.CharField(max_length=20, null=True)
    type_payment = models.CharField(max_length=50, null=True, blank=True)
    valute_card = models.CharField(max_length=10, null=True, blank=True)
    card_number = models.CharField(max_length=30, null=True, blank=True)
    date_card = models.CharField(max_length=20, null=True, blank=True)
    owner_card = models.CharField(null=True, max_length=100, blank=True)

    
    date_birthday = models.CharField(max_length=30, null=True, blank=True, verbose_name='Дата рождения')
    number_passport = models.CharField(max_length=20, null=True, blank=True, verbose_name='Серия и номер паспорта')
    date_passport = models.CharField(max_length=30, null=True, blank=True, verbose_name='Дата выдачи паспорта')
    who_gave = models.CharField(max_length=100, null=True, blank=True, verbose_name='Кем выдан')
    place_registration = models.CharField(max_length=100, null=True, blank=True, verbose_name='Место регистрации')
    email = models.CharField(max_length=100, null=True, blank=True, verbose_name='E-mail')
    bank = models.CharField(max_length=100, null=True, blank=True, verbose_name='Банк')
    reward = models.CharField(max_length=200, blank=True, null=True, verbose_name='Вознаграждение')
    passport_main_st = models.FileField(verbose_name='Паспорт главная ст.', blank=True)
    passport_st_registration = models.FileField(verbose_name='Паспорт ст. регистрации', blank=True)
    signed_contract = models.FileField(verbose_name='Подписанный договор', blank=True)


    inn = models.CharField(verbose_name="ИНН", blank=True, null=True, max_length=200)

    tg_phone_number = models.CharField(null=True, max_length=40, blank=True)

    comment = models.TextField(blank=True, null=True, verbose_name='Комментарии')
class sendmessage(models.Model):
    published = models.DateTimeField(db_index = True, null=True, auto_now_add=True)
    admin = models.CharField(max_length=50, null=True)
    select = models.CharField(max_length=50, null=True)
    message = models.TextField(max_length=500, null=True)
    user = models.CharField(max_length=50, null=True)



class happybirthday(models.Model):
    message = models.TextField(verbose_name='Текст для отправки', null=True)
    hour = models.CharField(max_length=10, null=True, verbose_name='')
    minute = models.CharField(max_length=10, null=True, verbose_name=':')    #verbose_name=':'

class contract(models.Model):
    file = models.FileField(upload_to='contract/main', null=True)


class Audio(models.Model):
    composition = models.CharField(null=True, max_length=200, verbose_name='Произведение')
    artist = models.CharField(null=True, max_length=100, verbose_name='Артист')
    autor_music = models.CharField(null=True, max_length=100, verbose_name='Автор музыки')
    autor_text = models.CharField(null=True, max_length=100, verbose_name='Автор текста')
    album = models.CharField(null=True, max_length=100, verbose_name='Альбом')
    isrc = models.CharField(null=True, max_length=100, verbose_name='ISRC (код)')
    genre = models.CharField(null=True, max_length=50, verbose_name='Жанр')

hello/templates/bot/account.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0036)https://example.elite-house.uz/users -->
<html lang="ru" style="height: auto; min-height: 100%;"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#f39c12">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/solid.css" integrity="sha384-ioUrHig76ITq4aEJ67dHzTvqjsAP/7IzgwE7lgJcg2r7BRNGYSK0LwSmROzYtgzs" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/fontawesome.css" integrity="sha384-sri+NftO+0hcisDKgr287Y/1LVnInHJ1l+XC7+FOabmTTIK0HnE2ID+xxvJ21c5J" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'hello/form.css' %}">
    <!-- AdminLTE styles -->
    <link rel="shortcut icon" href="{% static 'logo/LOGO_FINAL.ico' %}" type="image/ico">
    <link rel="stylesheet" href="{% static 'hello/AdminLTE.min.css' %}">
    <!-- AdminLTE skin styles -->
    <link rel="stylesheet" href="{% static 'hello/skin-yellow.min.css' %}">
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'hello/app.css' %}">
    <!-- Google Font -->
  <link rel="stylesheet" href="{% static 'hello/css.css' %}">
    <title> Отчеты</title>
</head>
<body class="skin-yellow sidebar-mini" style="height: auto; min-height: 100%;">
    <div class="wrapper" style="height: auto; min-height: 100%;">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <!-- Logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>Nevopartners</b></span>
                <!-- Logo for regular state and mobile devices -->
                <span class="logo-lg"><b>nevopartners</b></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button -->
                <a href="" class="sidebar-toggle fas fa-bars" data-toggle="push-menu" role="button"></a>
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar right menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li>
                            
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <!-- /.search form -->
                <!-- Sidebar menu -->
                <ul class="sidebar-menu accordion" id="accordion">
                    
                    <li class="header">НАВИГАЦИЯ</li>
                    
                    <li class=""><div class="link"><a> <i class="fa fas fa-stream"></i>Отчеты</a><i class="fa fa-chevron-down" style="color: white;"></i></div>
                        
                        <ul class="submenu">
                          <li><a href="/folder/"><i class="fa fas fa-stream" style="color: seashell;"></i>График отчетов</a></li>
                          <li><a href="{% url 'allaccount' %}"><i class="fa fa-file" style="color: seashell;"></i>Список отчетов</a></li>  
                          <li><a href="{% url 'createacc' %}"><i class="fa fa-plus" style="color: seashell;"></i>Добавить отчет</a></li>
                            
                        </ul>
                    
                    </li>
                  
                    <li class=""><div class="link"><a> <i class="fa fas fa-users"></i>Партнеры</a><i class="fa fa-chevron-down" style="color: white;"></i></div>
                        
                        <ul class="submenu">
                          <li><a href="/profiles/"><i class="fa fas fa-users" style="color: seashell;"></i>Все партнеры</a></li>
                            <li><a href="{% url 'createprof' %}"><i class="fa fa-plus" style="color: seashell;"></i>Добавить партнера</a></li>
                            
                            
                        </ul>
                    
                    </li>
                    

                    <li class=""><div class="link"> <a><i class=""></i>Обращения</a><i class="fa fa-chevron-down" style="color: white;"></i></div>
                      <ul class="submenu">
                        <li><a href="{% url 'sendmessage' 'all' 'no' %}"><i class="fa fa-envelope" style="color: seashell;"></i>Отправить сообщения</a></li>

                      </ul>
                      
                    </li>


                    <li class=""><div class="link"> <a><i class=""></i>Дополнительно</a><i class="fa fa-chevron-down" style="color: white;"></i></div>
                      <ul class="submenu">
                        
                        <li><a href="{% url 'calendar' %}"><i class="fa fa-calendar" style="color: seashell;"></i>Календарь</a></li>
                      </ul>
                      
                    </li>
                   

                    <li class=""><div class="link"> <a><i class="fas fa-sliders-h"></i>Настройки</a><i class="fa fa-chevron-down" style="color: white;"></i></div>
                      <ul class="submenu">
                        {% if user.is_superuser %}
                        <li><a href="{% url 'admins' %}"><i class="fas fa-user-shield" style="color: seashell;"></i>Все сотрудники</a></li>
                        {% else %}
                        {% endif %}
                        <li><a href="{% url 'editpassword' %}"><i class="fas fa-key" style="color: seashell;"></i>Смена пароля</a></li>
                        {% if user.is_superuser %}
                        <li><a href="{% url 'addadmin' %}"><i class="fas fa-plus" style="color: seashell;"></i>Добавить сотрудника</a></li>
                        <li><a href="{% url 'edit_contract' 1 %}" target="_blank"><i class="fas fa-file-signature" style="color: seashell;"></i>Шаблон контракта</a></li>
                        <li><a href="{% url 'updatehbd' 1 %}"><i class="fas fa-calendar-edit" style="color: seashell;"></i>Настройки календаря</a></li>
                        {% else %}
                        {% endif %}
                      </ul>
                      
                    </li>
                   

                    
                    
                </ul>
                               
            </section>
        </aside>
        <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="min-height: 813px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h3>
          Каталог
        
      </h3>
      <ol class="breadcrumb">
        
        
    <li class="active">Каталог</li>

      </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        
            
        
        
    <div class="row add-button">
        <div class="col-xs-4">
            <a href="{% url 'createacc' %}" class="btn btn-flat bg-orange"><i class="fas fa-plus"></i>Добавить отчет</a>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-12">
            <div class="box">
                <div class="box-header">
                    
                    <div class="box-tools">
                        <div class="input-group input-group-sm" style="width: 150px">
                            
                        </div>
                    </div>
                </div>
                <div class="box-body table-responsive no-padding">
                    <table class="table table-hover" id="userTable">
                        <thead>
                            <tr>
                                <th>№</th>
                                <th>Дата создания</th>
                                <th>Псевдоним</th>
                                <th>Год</th>
                                <th>Месяц</th>
                                <th>Сумма</th>
                                <th>Статус</th>
                                <th>Отчет</th>
                              
                            </tr>
                        </thead>
                        <tbody>
                            {% for a in accounts %}
                            <tr>
                   
                                <td>{{ forloop.counter }}</td>
                                <td>{{ a.published }}</td>
                                <td>{{ a.pseudonym }}</td>
                                <td>{{ a.year }}</td>
                                <td>{{ a.month.month }}</td>
                                <td>{{ a.summa }}</td>
                                <td>
                                  {% if a.status.s == 'В работе' %}
                                  ▶️
                                  
                                  {% elif a.status.s == 'В ожидании' %}
                                  ⏳
                                  {% elif a.status.s == 'Оплачен' %}
                                  ✅
                                  {% elif a.status.s == 'Отклонена' %}
                                  ❌
                                  {% elif a.status.s == 'Не оплачен' %}
                                  🔒
                                  {% elif a.status.s == 'Перенесена' %}
                                  ⏱
                                  {% else %}
                                  🔒
                                  {% endif %}
                                
                                
                                
                                
                                  {{ a.status.s }}
                                </td>
                                <td><a href="{% url 'edit' a.pk %}" class="btn btn-danger btn-flat">Показать</a>
                                    {% if perms.hello.delete_account %}
                                    <a href="{% url 'deleteacc' a.pk %}" class="btn btn-danger btn-flat"><i class="fas fa-trash" aria-hidden="true"></i></a>
                                    {% else %}
                                    {% endif %}
                                </td>
                            </tr>
                            {% endfor %}
                
                          
                            
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>

    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Административная панель
    </div>
    <!-- Default to the left -->
    <strong>Copyright © 2020 VID.</strong> <small>Все права защищены.</small>
  </footer>
    </div>



    <script src="{% static 'hello/adminlte.min.js' %}"></script>
     <script src="{% static 'hello/jquery.min.js' %}"></script>



</body></html>

hello/templates/bot/security.html
{% load static %}
<!DOCTYPE html>
<!-- saved from url=(0036)https://example.elite-house.uz/users -->
<html lang="ru" style="height: auto; min-height: 100%;"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    
    <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <meta name="theme-color" content="#f39c12">
    <link rel="stylesheet" type="text/css" href="{% static 'hello/form.css' %}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css" integrity="sha384-HSMxcRTRxnN+Bdg0JdbxYKrThecOKuH5zCYotlSAcp1+c8xmyTe9GYg1l9a69psu" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/solid.css" integrity="sha384-ioUrHig76ITq4aEJ67dHzTvqjsAP/7IzgwE7lgJcg2r7BRNGYSK0LwSmROzYtgzs" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/fontawesome.css" integrity="sha384-sri+NftO+0hcisDKgr287Y/1LVnInHJ1l+XC7+FOabmTTIK0HnE2ID+xxvJ21c5J" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'hello/form.css' %}">
    <!-- AdminLTE styles -->
    <link rel="shortcut icon" href="{% static 'logo/LOGO_FINAL.ico' %}" type="image/ico">
    <link rel="stylesheet" href="{% static 'hello/AdminLTE.min.css' %}">
    <!-- AdminLTE skin styles -->
    <link rel="stylesheet" href="{% static 'hello/skin-yellow.min.css' %}">
    <!-- Custom styles -->
    <link rel="stylesheet" href="{% static 'hello/app.css' %}">
    <!-- Google Font -->
  <link rel="stylesheet" href="{% static 'hello/css.css' %}">
    <title> Вход</title>
</head>
<body class="skin-yellow sidebar-mini" style="height: auto; min-height: 100%;">
    <div class="wrapper" style="height: auto; min-height: 100%;">
        <!-- Main Header -->
        <header class="main-header">
            <!-- Logo -->
            <a href="" class="logo">
                <!-- Logo for sidebar mini 50x50 pixels -->
                <span class="logo-mini"><b>Nevopartners</b></span>
                <!-- Logo for regular state and mobile devices -->
                <span class="logo-lg"><b>Nevopartners</b></span>
            </a>
            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button -->
                
                <!-- Navbar right menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <li>
                            
                        </li>
                    </ul>
                </div>
            </nav>
        </header>
        <aside class="main-sidebar">
            <section class="sidebar">
                <!-- /.search form -->
                <!-- Sidebar menu -->

                </ul>
            </section>
        </aside>
        <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper" style="min-height: 813px;">
    <!-- Content Header (Page header) -->
    <section class="content-header">
      <h3>
        
        
      </h3>
      <ol class="breadcrumb">
        
        
    <li class="active"></li>

      </ol>
    </section>
    <!-- Main content -->
    <section class="content container-fluid">
        
        <div class = "login-page">
            <div align = center>{{ message }}</div>
            <div class="form">
                <form method = "post" enctype="multipart/form-data" class="login-form">
                    {% csrf_token %}
                    {{ form.as_p }}
                    <button>Ок</button>
                </form>
            </div>
        </div>
    </section>
    <!-- /.content -->
  </div>
  <!-- /.content-wrapper -->

  <!-- Main Footer -->
  <footer class="main-footer">
    <!-- To the right -->
    <div class="pull-right hidden-xs">
      Административная панель
    </div>
    <!-- Default to the left -->
    <strong>Copyright © 2020 VID.</strong> <small>Все права защищены.</small>
  </footer>
    </div>


    <script src="{% static 'hello/jquery-3.3.1.slim.min.js' %}"></script>
    <script src="{% static 'hello/bootstrap.min.js' %}"></script>
    <script src="{% static 'hello/adminlte.min.js' %}"></script>
    
    <script src="{% static 'hello/users.js' %}"></script>


</body></html>

hello/templates/bot/upload.html
{% extends 'layout/basic.html' %}
{% block con %}
  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Upload</button>
  </form>



{% endblock %}